SELECT
    LEFT(CONVERT(VARCHAR(8), GIN_Date), 4) + '-' + SUBSTRING(CONVERT(VARCHAR(8), GIN_Date), 5, 2) + '-' + RIGHT(CONVERT(VARCHAR(8), GIN_Date), 2) AS Date,
    ROUND(SUM(Inv_Nett), 2) AS Purchases
FROM PurMastTable
WHERE
    GIN_Date BETWEEN
        (CASE WHEN MONTH(GETDATE()) <= 3 THEN YEAR(GETDATE()) - 1 ELSE YEAR(GETDATE()) END) * 10000 + 401
        AND (CASE WHEN MONTH(GETDATE()) <= 3 THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()) + 1 END) * 10000 + 331
GROUP BY GIN_Date
ORDER BY Date DESC
