SELECT
    LEFT(CONVERT(VARCHAR(8), Bill_Date), 4) + '-' + SUBSTRING(CONVERT(VARCHAR(8), Bill_Date), 5, 2) AS Month,
    ROUND(SUM(Bill_Nett) / 100000, 2) AS Sales
FROM BillMastTable
WHERE
    Bill_Date BETWEEN
        (CASE WHEN MONTH(GETDATE()) <= 3 THEN YEAR(GETDATE()) - 1 ELSE YEAR(GETDATE()) END) * 10000 + 401
        AND (CASE WHEN MONTH(GETDATE()) <= 3 THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()) + 1 END) * 10000 + 331
GROUP BY LEFT(CONVERT(VARCHAR(8), Bill_Date), 4) + '-' + SUBSTRING(CONVERT(VARCHAR(8), Bill_Date), 5, 2)
ORDER BY Month DESC
