SELECT
    ROUND(SUM(Inv_Nett) / 100000, 2) AS TotalPurchases
FROM PurMastTable
WHERE
    GIN_Date BETWEEN
        (CASE WHEN MONTH(GETDATE()) <= 3 THEN YEAR(GETDATE()) - 1 ELSE YEAR(GETDATE()) END) * 10000 + 401
        AND (CASE WHEN MONTH(GETDATE()) <= 3 THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()) + 1 END) * 10000 + 331
